---
title: دليل لبلادي 3.0
hero_image: images/banner.png
description: Add nice layouts and cool effects to your website!
theme: أحمر #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: مشاريع كودردوجو (CoderDojo)
software: html-css-javascript
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: المقدمة
  - 
    title: الحصول على الإعدادات
  - 
    title: بطاقات قابلة للنقر
  - 
    title: جميع مافي الصف
  - 
    title: اجعل قائمتك قابلة للاستجابة
  - 
    title: التسميات التوضيحية والملاحظات الجانبية
  - 
    title: تصميم تخطيط صفحة رائع
  - 
    title: Photo collage
  - 
    title: مؤثرات خاصة
